# docker-composerリファレンス和訳 
# https://qiita.com/zembutsu/items/9e9d80e05e36e882caaa
version: '2'

services:

  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - "./.env.dev"
    environment:
      - "WEBPACKER_DEV_SERVER_HOST=webpack"
    volumes:
      - ".:/app"
      # マウントを上書き
      - /app/tmp
      - /app/log
      - /app/.git
      - /app/vendor      
    # 他のサービスやコンテナから全てマウントする
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  webpack:
    <<: *app_base
    # このコマンドでvueのファイルを自動コンパイル(変更されたタイミングで)できる。
    command: "bin/webpack-dev-server"
    environment:
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"
    ports:
      - "3035:3035"
    depends_on:
      - db
    tty: false
    stdin_open: false

  db:
    # 実行時に再起動するかどうか(今回はdockerをビルド時や立ち上げる際にMYSQLを再起動、という意味)
    restart: always
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes_from:
      - data
    ports:
      - "4306:3306"

  # dataコンテナを用いてmysql, gem, node_moduleなどをコンテナ内にキャッシュしておくことでbuild時の再インストールを防ぐ。
  data:
    image: "busybox"
    volumes:
      - db:/var/lib/mysql
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules

volumes:
  db:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
